CREATE TABLE "User" (
	"Userid"	INTEGER NOT NULL UNIQUE,
	"Name"		TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	"Mobile"	TEXT NOT NULL,
	"Isadmin"	INTEGER NOT NULL,
	"Status"	INTEGER NOT NULL,
	PRIMARY KEY("Userid" AUTOINCREMENT)
);